CREATE TABLE `holidays` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `HOLIDAY_DATE` DATETIME NULL,
  `DESCRIPTION` VARCHAR(45) NULL,
  `IS_ACTIVE` BIT(1) NULL,
  `SCHOOLID` INT NOT NULL,
   `created_date` datetime NOT NULL,
  `created_user` varchar(45) NOT NULL,
  `last_updated_date` datetime NOT NULL,
  `last_updated_user` varchar(45) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `SCHOOLID_idx` (`SCHOOLID`),
  CONSTRAINT `SCHOOLID_idx`
    FOREIGN KEY (`SCHOOLID`)
    REFERENCES `school` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE `leaves` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `LEAVE_DATE` DATETIME NULL,
  `DESCRIPTION` VARCHAR(1000) NULL,
  `IS_ACTIVE` BIT(1) NULL,
  `SCHOOLID` INT NOT NULL,
  `USERID` INT NOT NULL,
   `created_date` datetime NOT NULL,
  `created_user` varchar(45) NOT NULL,
  `last_updated_date` datetime NOT NULL,
  `last_updated_user` varchar(45) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `USERID_idx` (`USERID`),
  KEY `SCHOOLID_idx` (`SCHOOLID`),
  CONSTRAINT `USERID`
    FOREIGN KEY (`USERID`)
    REFERENCES `user` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `SCHOOLID_idx1`
    FOREIGN KEY (`SCHOOLID`)
    REFERENCES `school` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;